name: google_mobile_ads_pangle
description: Google Mobile Ads mediation plugin for Pangle.
version: 2.2.0

environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.androidhuman.plugins.google_mobile_ads_pangle
        pluginClass: GoogleMobileAdsPanglePlugin
      ios:
        pluginClass: AHMGoogleMobileAdsPanglePlugin
